### ISSUE TITLE
Unable tou use h key

### ISSUE THREAD

**Issue by jacob-d242** [egaga/openvim#103]
The h key is not working,i have tried pressing it severally but it doesn't respond

**Comment by egaga** [comment]
What is your 1) browser and 2) operating system?

**Comment by jacob-d242** [comment]
Am using Brave on Ubuntu

**Comment by egaga** [comment]
Sorry don't have that environment and not going to bother install virtualbox etc.
Maybe some plugin is capturing that key event... but quick look at shortcut references didn't give any clue.

**Comment by gmaggess** [comment]
I have the same issue in Chrome 113.0.5672.92 and MacOS Ventura.

**Comment by egaga** [comment]
Does it work in the sandbox? https://openvim.com/sandbox.html
or basic movement section? 
<img width="324" alt="image" src="https://github.com/egaga/openvim/assets/138295/9534d475-db55-4f3f-bd84-a89da0058071">


Couldn't yet reproduce in macos Chrome.
