### ISSUE TITLE
Enter key not reacting

### ISSUE THREAD

**Issue by Olaf849** [egaga/openvim#104]
Hi there, it looks like it could be an excellent app, but the touch enter doesn't work on Android phone. 
I did try horizontal or vertical and zoomed in or out, nothing seemed to work.
Thanks

**Comment by unelma** [comment]
Sorry, but this has not been designed mobile-use in mind. Maybe it could be made to work, but any kind of proper development of this project has stalled long ago.

Thank you for the report anyway.
