### ISSUE TITLE
Undo multiple actions

### ISSUE THREAD

**Issue by Omcsesz** [egaga/openvim#109]
Hello, Team!

According to this site, undoing multiple actions is also achievable in vim:
https://phoenixnap.com/kb/vim-undo-redo

Can you please add this functionality to the tutorial?

**Comment by egaga** [comment]
Yes, that's a valid idea, but I'll try to keep the tutorial implementation limited to existing features, because that I don't have the motivation to develop it further.
Thank you for bringing it up.
