### ISSUE TITLE
practice modes vanishes 

### ISSUE THREAD

**Issue by kalim-Asim** [egaga/openvim#122]
when i try to reload practice page  i am getting blank white screen. Thanks for this though ! <3

**Comment by unelma** [comment]
It seems that that happens quite frequently, thank you for reporting. (Though not sure if will be fixed, as development is stalled.)

(The problem could be that scripts are not ensured to wait the external dependencies.)

**Comment by egaga** [comment]
Should work now because of https://github.com/egaga/openvim/pull/123/commits/be61dcb11f4d3fc5eafce9dd99cbf46d8edd39a6
