### ISSUE TITLE
Incorrect keyboard layout

### ISSUE THREAD

**Issue by jasonganub** [egaga/openvim#21]
The keyboard number section at the top repeats 4 and 5.  Not sure if it's a local issue or not but it doesn't allow me to get further than half the tutorial.

![capture](https://cloud.githubusercontent.com/assets/5640407/14263894/1e090016-fa72-11e5-8d56-30a3f4937f99.PNG)

**Comment by ronrihoo** [comment]
@jasonganub, good eye!

This has been recently addressed by #41; however, the modification is combined with an enhancement, which requires @egaga's approval. 

If the pull request is declined, then I'll make a separate one to address the repeated keys separately.

**Comment by jasonganub** [comment]
@ronrihoo Thanks for following up

**Comment by GabrielSturtevant** [comment]
This issue was has been resolved and should be closed

**Comment by unelma** [comment]
Thanks for mentioning.
