### ISSUE TITLE
Section 12 doesn't allow for any user input

### ISSUE THREAD

**Issue by theasianpianist** [egaga/openvim#38]
The website doesn't allow me to type anything at all once I get to section 12. I've tried switching between both Dvorak and Qwerty keyboard layouts to type the "&" symbol. The shift and 7 key are highlighted so I think that's what I'm supposed to press, but nothing happens after I do.

**Comment by ronrihoo** [comment]
@theasianpianist, you have the right idea. It's just that section 12 is referring to the forward slash, '/', character. I'm a visual learner myself, so I feel for you.

The virtual keyboard appears to be based on the Finnish-Swedish keyboard layout, which implements SHIFT-7 for the forward slash character.

![finnish_keyboard_layout](https://user-images.githubusercontent.com/13303536/29499624-581db594-85db-11e7-9b4a-f234cbffcbe7.png)

Many other keyboard layouts, such as the US keyboard, implement SHIFT-7 for the ampersand, '&', character.

![us_keyboard_layout](https://user-images.githubusercontent.com/13303536/29500144-646134e0-85e3-11e7-98d7-ec1d6ebf4b14.png)

So sending the forward slash character will invoke the tutorial to continue normally.

**Comment by ronrihoo** [comment]
@egaga, given issues #2, #5, #7, #10, #11, #21, #23, #29, #32, #38, and #40 — which are all raised by section 12's indication to press the SHIFT-7 key combination — if I may, then I recommend the following modification to be made in **virtual_keyboard.js**, starting at line 23 (see pull request #41).

```js
var numberRow = ['hid', two('1', '!'), two('2', '"'),
    two('3', '#'), two('4', '$'), two('5', '%'),
    two('6', '&'), two('7', '/'), two('8', '('), 
    two('9', ')'), two('0', '=')];
```

This will allow the user to realize that the virtual keyboard layout is different from his/hers and that section 12 is indicating to send the forward slash, '/', character. Those who do not speak/read English may especially benefit from this visual aid enhancement.

It also removes the repeated number keys, as mentioned in issue #21.

![image](https://user-images.githubusercontent.com/13303536/29499553-9a9667d8-85d9-11e7-8987-41f2801f27a2.png)

**Comment by unelma** [comment]
This was merged.
