### ISSUE TITLE
'a' in command mode takes me to insert mode (practice screen)

### ISSUE THREAD

**Issue by BCza** [egaga/openvim#44]

**Comment by pauloue** [comment]
This is expected behavior. 'a' inserts (appends) text after the cursor, while 'i' inserts text before the cursor.
Here's a nice reference sheet: http://tnerual.eriogerg.free.fr/vimqrc.html

**Comment by BCza** [comment]
Ok, thanks. Sorry for the spam, I'm *very *new to vim. I love your tutorial
though :)
