### ISSUE TITLE
Section 3 is not working

### ISSUE THREAD

**Issue by webbydoug** [egaga/openvim#50]
I'm using Chrome Version 62.0.3202.62 (Official Build) (64-bit)

When I press the h key nothing happens.

**Comment by egaga** [comment]
I have the exact same version (Macos) and it works.
Does it work with some other browser?

**Comment by egaga** [comment]
Also try to skip to other section (see right index on the right side of the site).
Do you have problems with any other section?

Or go to the "practice" (see link at the top of the page). Does `h` work there?

**Comment by webbydoug** [comment]
I think I figured it out. The app worked in Safari and Firefox. I have Vimium installed in Chrome. I excluded the hjkl keys and now it works in Chrome. One thing that comes to mind is that I have remapped my esc key to the Caps lock key. The app does not take this into consideration when going through exercises. Love the app!

**Comment by egaga** [comment]
Okay, good to know, thanks!
