### ISSUE TITLE
Crashed on doing `10000i-`

### ISSUE THREAD

**Issue by imvpn22** [egaga/openvim#52]
I was trying to insert 10000 `-` using the command `10000i-` followed by `esc` key.
First I did `1000i-` which took an approx 3-4 sec to respond. Then I thought on how much value will it crash so I tried with 10000 and it looks that site is crashed, I am unable to click anywhere on the screen.

Is it a bug or I am pushing it hard?

**Comment by imvpn22** [comment]
Also, it's not loading when I press refresh button after the crash.

**Comment by egaga** [comment]
Yeah, it's not really meant for that kind of usage. If it were, the code would be modelled differently.
