### ISSUE TITLE
Cursor won't move using Programmer Dvorak keyboard

### ISSUE THREAD

**Issue by blaisck** [egaga/openvim#53]
Hello, I'm using Programmer-Dvorak keyboard in Windows 10 Pro 64-bit. 
When I go to `hjkl` step, the cursor won't move, maybe you can help me.

**Comment by unelma** [comment]
I have no idea why that could be. I'll close this now because no relevant information how I could figure this out.

Btw. the dvorak layout is now supported.
https://openvim.com/?layout=dvorak
