### ISSUE TITLE
Could not use the 'h' key when prompted

### ISSUE THREAD

**Issue by DerekWW** [egaga/openvim#59]
I was unable to press the `h` key when prompted at the second section that introduces the h j k l movement keys.

**Comment by halink0803** [comment]
I got the same problem today. I think there are people also face the same problem. Can you guys please take a look?

**Comment by egaga** [comment]
Do you have caps lock on? I couldn't reproduce the issue on Chrome or Firefox on my MacBook.

**Comment by halink0803** [comment]
> Do you have caps lock on? I couldn't reproduce the issue on Chrome or Firefox on my MacBook.

I have checked it, caps lock does not on. Maybe because of some extension I installed in my Chrome. I have vimium installed in my Chrome.

**Comment by egaga** [comment]
Well, I think there's no problem, I cannot do anything about that. You need to disable Vimium if you use OpenVim. Thanks!

**Comment by halink0803** [comment]
> Well, I think there's no problem, I cannot do anything about that. You need to disable Vimium if you use OpenVim. Thanks!

I think you could improve the instruction by adding notice or warning about disable Vimium or better solve the app conflict with extensions. When I faced the problem the first time, it is really annoying that it just does not work.

**Comment by egaga** [comment]
I can symphatize with that but sounds like implementing that kind of hackish check is just covering a problem that Vimium user should learn anyways.
