### ISSUE TITLE
open bugs link in new window.

### ISSUE THREAD

**Issue by gurrrung** [egaga/openvim#65]
Wouldn't it be great if clicking on bugs should open a new window in the place of opening the link in same window as sometimes user click on them in curiousity and losts the progress done.

**Comment by egaga** [comment]
Maybe. FWIW, if they lose progress, there's the menu to get back to any section.

**Comment by gurungrahul2** [comment]
but its still sounds like a better idea to have a new window.

**Comment by egaga** [comment]
Decision is: no.
