### ISSUE TITLE
Website crashed (and sent me here)

### ISSUE THREAD

**Issue by renich** [egaga/openvim#74]
I was just doing the exercise on my browser. I am using Fedora 31 and firefox-70.0-1.fc31.x86_64

**Comment by egaga** [comment]
Could not reproduce with Firefox 70.0. However, the search section does not
work because pressing the slash, i.e. /, opens up Firefox search.

What section you were on?
The site shouldn't send you on Github issue tracker automatically. Were you
on www.openvim.com or othersite that hosts OpenVim?

**Comment by renich** [comment]
OK, so, what must've happend is that I hit tab and clicked the report bug link by accident. 

The section, I don't quite recall. I think it must've been one of the last sections.

**Comment by unelma** [comment]
Closed until reproduced.
