### ISSUE TITLE
Typing regular characters in the tutor on Firefox causes text searching

### ISSUE THREAD

**Issue by rhithyn** [egaga/openvim#81]
Trying to run the OpenVim tutorial on Firefox 80.0.1 on Windows 10 and when I got to the "insert mode" tutorial, pressing "i" started a firefox page search.  Further testing, every time I type a regular character, the firefox search takes over after the first character and won't work with OpenVim.
![searchingpopup](https://user-images.githubusercontent.com/198138/94146927-73e93900-fe29-11ea-8909-c29188a4f114.jpg)

**Comment by egaga** [comment]
Hi, this was news to me, but if browser takes over key binding for itself, I think I cannot help in any reasonable way.

Perhaps this might fix the issue for you: https://support.mozilla.org/en-US/questions/1284607

**Comment by rhithyn** [comment]
> Perhaps this might fix the issue for you: https://support.mozilla.org/en-US/questions/1284607

That looks like the solution, thank you!
