### ISSUE TITLE
wow! that is really cool

### ISSUE THREAD

**Issue by stub-official-band** [egaga/openvim#83]
How did you **GET THE TEXT TO WRITE ACROSS THE SCREEN LIKE THAT** `That is literally amazing`
Wish there was a way to do that in python... wait there is! have to do it letter by letter tho.

**Comment by unelma** [comment]
Well, it was done letter by letter. Those letters are represented as styled html elements.
Timing was done using: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

So there is no out-of-the-box sequenced text system but I built a small custom engine. It's a little bit involved, one reason being that it is implemented using continuation-passing-style https://github.com/egaga/openvim/blob/master/js/tutorial/tutorial_engine.js

**Comment by stub-official-band** [comment]
thanks! Keep doing what your doing!
