### ISSUE TITLE
/ in firefox opens firefox quicksearch, I need a way to skip past it.

### ISSUE THREAD

**Issue by thegreedyturtle** [egaga/openvim#92]
Needs some button controls to skip tutorials so I can get past some.

**Comment by unelma** [comment]
Hi, click on the menubar to select section.
![image](https://user-images.githubusercontent.com/46071946/140819116-df29198d-9520-4696-a39b-62da2dc7076a.png)

**Comment by thegreedyturtle** [comment]
Thanks

**Comment by thegreedyturtle** [comment]
Great tutorial btw!

**Comment by unelma** [comment]
Thank you, appreciated!
